### ISSUE TITLE
Missing content in "Basic information"

### ISSUE THREAD

**Issue by estwestminimu** [reactjs/pl.reactjs.org#349]
Hey, in the React documentation in Polish I discovered that there are several sections missing from the "Podstawowe informacje" tab such as: 
"Ucz się Reacta",
"Bądź na bieżąco",
"Dokumentacje wersji" and
"Czegoś brakuje?"
![react](https://user-images.githubusercontent.com/96234081/175351049-4a622bc7-4f9e-4f65-aa1b-83c43fdbe0ba.PNG)

**Comment by jakubdrozdek** [comment]
@estwestminimu Thanks for pointing that out! I just fixed it. Apparently, there was a `<script>` tag in the text, which was interpreted as a real, unclosed HTML tag.
