### ISSUE TITLE
Polish Translation Final Steps

### ISSUE THREAD

**Issue by tesseralis** [reactjs/pl.reactjs.org#66]
Congrats on almost finishing the core of the Polish translation! There are a couple more tasks we need to do before we mark the core pages as complete.

* [x] Change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25) . One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program)
* [x] Go over the pages of the site one last time to check for consistency

**Comment by tesseralis** [comment]
The only real issue I found was that the header is kind of cut off -- you could fix this by decreasing the right margin on the "React" logo and/or decreasing the padding on the nav links.

<img width="1280" alt="Screen Shot 2019-04-02 at 5 20 54 PM" src="https://user-images.githubusercontent.com/1278991/55444641-47be6600-556c-11e9-87d7-42eceb590231.png">

**Comment by g12i** [comment]
Reopening in order not to forget about DocSearch API key.

**Comment by cvqprs** [comment]
I'm going to close this ticket as the core part is 💯%
