### ISSUE TITLE
Create a New React App page - formatting issue

### ISSUE THREAD

**Issue by cvqprs** [reactjs/pl.reactjs.org#73]
The is an issue with of note section

Original:
![Screenshot 2019-04-16 at 17 09 00](https://user-images.githubusercontent.com/2962638/56212085-604d7680-606a-11e9-8fcf-a3ad224a15de.png)

Polish version:
![Screenshot 2019-04-16 at 17 09 07](https://user-images.githubusercontent.com/2962638/56212099-67748480-606a-11e9-9dec-86eb0f0dbef4.png)

**Comment by jakubdrozdek** [comment]
It's caused by an extra line in between those two.

**Comment by cvqprs** [comment]
Fixed in #78
